### ISSUE TITLE
Report Sidebar

### ISSUE THREAD

**Issue by FlowOverFail** [RelaxedJS/ReLaXed#17]
When using the:  ".report-sidebar: p [Text-Here]" I am unable to get the sidebar on the second page of the PDF.  I used Git to clone the example and worked straight from there.

Any help would be appreciated, thanks!

**Comment by FlowOverFail** [comment]
@Zulko I cloned from the report example so my .scss file is exactly like the example.  The example-generated PDF file contains the sidebar on every page, but using the .pug in atom (along with the relaxed ./report.pug) it generates a PDF with the sidebar on the first page only.  Can you take a quick look at using the example provided for report>

**Comment by Zulko** [comment]
oh i get it. I'll have a look

**Comment by FlowOverFail** [comment]
@Zulko Thank you very much!  Looking forward to writing a report for my research paper for school.  Thanks for your time, cheers!

**Comment by FlowOverFail** [comment]
@Zulko I tried installing this on my Desktop and got the following errors:

First error:

- Processing detected change in \report.pug...
- CHTML - Unknown character: U+FFFD in MathJax_Main,MathJax_Size1,MathJax_AMS
- CHTML - Unknown character: U+10 in MathJax_Main,MathJax_Size1,MathJax_AMS

Second error:

- TeX parse error: Undefined control sequence \�
- Formula )�ً�TX��a����js5�╚V�FJa�],�\���&6���>֢zX��N��n#ml�Zw2�L�V�n.]╚�C�y
-                                                                           ����*�:����o�����_�q�ބs�.Hg�R�n��
-                                                                                                             5p�������
-                                                                                                                      m��5���潦�ڞ�ia�T?
- K�=�].�]��ն╔�M�
-                 ��rL7�\㘳�B
- �տ)� contains the following errors:
-  [ 'TeX parse error: Undefined control sequence \\�' ]

**Comment by FlowOverFail** [comment]
@Zulko I also just tried installing this on a new Ubuntu Desktop VM with everything updated.  Same results are produced for me.

**Comment by benperiton** [comment]
I have the same issue, and it seems to be related to versions of Puppeteer > 1.0.0
If I change package.json to "puppeteer": "1.0.0" then it works just fine.

**Comment by Zulko** [comment]
Thanks @benperiton , this is very bad news, I love that sidebar, and the general idea to "watermark" every page with a constant element. My best guess is that there was a change in the way the most recent versions of Chromium print PDFs. That would be sad. For instance Weasyprint (for python) also considers that "position: fixed" elements should appear on every page.

Last resort, I'll freeze pupetteer to 1.0, but I'm not sure if it could clash with other libraries in global installs.

**Comment by benperiton** [comment]
Having a little play, it seems it is related to
```
-webkit-transform-origin: 10px 10px;
transform: rotate(-45deg);
```

If those are removed, then the 'watermarking' works fine - as in it appears on every page.

**Comment by Zulko** [comment]
Sounds less desperate than I thought. Thanks for finding that there are rendering differences in the most modern versions of puppeteer, hopefully they can all be fixed by amending the CSS.

**Comment by FlowOverFail** [comment]
@benperiton @Zulko Thank you for looking into it more.  Even when installing Puppeteer 1.0.0, I still cannot get the sidebar to be on every page.  I tried commenting out those two lines you mentioned as well, and the sidebar side not appear where it normally did, nor did it look good.

**Comment by Zulko** [comment]
I believe what @benperiton meant is that, when you remove these two lines, despite not looking good (because it is not rotated), the sidebar at least appears on every page . Can you confirm that ?

**Comment by FlowOverFail** [comment]
@Zulko For me, the sidebar appeared half way between the first page and the second page, but it was centered horizontally.  Also, the second page only included like 20% of the sidebar, and everything else was cut off.

**Comment by benperiton** [comment]
Yep.

@FlowOverFail So with a fresh clone from here, and a clone of the examples repo, start up ```relaxed report.pug``` then edit report.scss and remove
```
-webkit-transform-origin: 0 0;
  transform: rotate(-90deg);
```
Save it and then open the pdf and at the bottom of each page there is a pink area - that is the sidebar but obviously not rotated.


Did you remove the package-lock.json and node_modules, edit the package.json to be ```"puppeteer": "1.0.0"``` then ```npm install```? That worked for me to get the older version. 

Otherwise you can try doing the PUPPETEER_CHROMIUM_REVISION thing and then modifying the puppeteer Luancher.js to accept it.

**Comment by benperiton** [comment]
@FlowOverFail That is because the styles are set for it being rotated, in order to get it to display properly, you either need to use an older version, or create a new style that doesn't use ```transform: rotate``` - as that seems to be the issue

**Comment by FlowOverFail** [comment]
@benperiton I manually installed puppeteer 1.0.0 using NPM via CMD. Are you saying that I'll need to "remove the package-lock.json and node_modules, edit the package.json to be "puppeteer": "1.0.0" then npm install" in order to use the sidebars as they were intended?

Is manually installing puppeteer 1.0.0 not sufficient enough? Using NPM list only shows 1.0.0.

**Comment by Zulko** [comment]
I had a look and it looks to me like a Chromium bug: fixed elements will appear on every page, unless they have a ``transform:rotate``, at which case they will only appear on the first page. This is a regression that happened between chrome 65 and 67. I file a bug report:

https://bugs.chromium.org/p/chromium/issues/detail?id=839424

**Comment by Zulko** [comment]
So it is indeed a bug from Chromium 67. It is unclear how easy it can be fixed on their end, but they   proposed a workaround using ``writing-mode: vertical-rl`` instead of ``transform:rotate``, which works fine (thanks Xianzhu), except that the sidebar text now reads top to bottom instead of bottom to top (I prefer the former way). Small price to pay imho, and it makes the CSS easier to understand. I updated the example with that workaround.

**Comment by Zulko** [comment]
Closing this as the changes in the examples repo removes the problem.
